### ISSUE TITLE
[NOTÍCIAS] Criar single

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#31]
- [x] Criar estrutura 
- [x] Aplicar layout
- [x] Componente de redes sociais
- [x] Listagem de notícias
Layout:
https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-12861&t=OGZiRncasaOS3AhD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by caio-ascava** [comment]
**1.	Ícone do Facebook, canto superior esquerdo, está diferente do Figma;
2.	Ícone de lista, canto superior direito, está maior que Figma.**
DEV:
 ![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e7a6a674-9a55-495b-a9f3-058f4fd221c4)
Figma:
 ![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/68095ae0-918a-4aab-b2e5-c90b8c09b67e)

**1.	Falta adicionar horário e ícone relógio
2.	Falta adicionar os ícones (Instagram, Facebook, Whatsapp, Twitter e compartilhar)**
DEV:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/dd92ae67-c91d-4bf8-bec0-3c76d38ac1c3)
Figma:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/71684deb-8cc1-4b9a-88aa-e75d118348f4)

**1.	No DEV apresenta um texto diferente do título anunciado. Mas no Figma, este subtítulo não existe.
2.	A entrevista completa, não foi possível validar pois na base DEV não há estas informações.**
DEV:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/59512244-3e7d-4b9e-b7b5-7861d62bbb3a)
Figma:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c960dd30-1c83-429e-84d6-15d067b35e8a)

Essa é uma dúvida minha, pois quando eu minimizo a tela do computador e ajusto o tamanho dela, as palavras juntam na barra de separação. Mas eu acredito que elas deveriam permanecer centralizadas, sendo necessário arrastar a tela para visualizar as demais.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/34bee833-c113-44e9-8d16-8fe550f1ab51)

Cor do plano de fundo no Figma está #F5F5F5 (cinza bem claro) e no Dev está branco.

**Comment by daphnemartinsba** [comment]
- [ ] Alterar cor da fonte do título para #262626
- [ ] Alterar cor da fonte do nome do autor para #000000
- [ ] Background da página deve ser f5f5f5: atualmente o menu está como #f5f5f5, menu deve estar com a cor #848484
- [ ] Adequar ícones de compartilhamento no corpo do texto ao do figma
- ícones do dev:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/1a662dbb-307b-4ae5-8401-1e3127f70517)
- ícones do figma:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/2acaf76b-02d6-4a25-99a5-cc3735117173)

- [ ] Sub títulos da notícia: alterar lineheight para 162.5% ou 26px:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a054753b-8eeb-461c-af96-c8d154b60637)


- [ ] 1366 e 1920: imagem do corpo do texto deve ser alinhada ao corpo do texto, no dev ela está maior. Ex: https://dev.midianinja.org/hacklab/teste-single-noticias-com-tematica-lgbtqia-escritora-daphne-zanelato-desafia-padroes-com-marteus/
- [ ] Adequar ícones de compartilhamento do fim da página aos do figma:
- no dev:  
![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/45f1db76-f980-46d1-a964-544eba37afa4)
- no figma:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a1a22d18-091b-44a5-906e-1bfcbc01de64)

- [ ] Retirar um separador do fim do texto, após ícones de compartilhamento (caso o comentário do facebook permaneça aí ele será readicionado)
- [ ] Alterar lineheight para 26px ou 162.5% título de notícias relacionadas
- [ ] thumbs de notícias relacionadas devem direcionar para os posts das notícias
- [ ] alterar line height para 18.85px
- [ ] Inserir anúncio no meio do texto:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/97992744-c347-4e51-816d-81ab717e75c4)

- [ ] 1366: adequar posição das thumbs

**Comment by daphnemartinsba** [comment]
- Retornos na issue #48
